### ISSUE TITLE
Make a release, please

### ISSUE THREAD

**Issue by compartia** [nemoware/document-parser#1]
@SergeyShalaevsky Sergey, could you please make a jar and "release" it?
here : https://github.com/nemoware/document-parser/releases
Thanks!

(cannot do it myself for some reason)

`invalid target release: 12`
<img width="657" alt="Capture d’écran 2019-08-09 à 18 14 55" src="https://user-images.githubusercontent.com/7677437/62789511-b50d7500-bad1-11e9-8fe7-87d359dcda75.png">

**Comment by SergeyShalaevsky** [comment]
У тебя не собирается из-за старой версии java.
Сделал релиз, но тебе все равно надо ставить 12 версию java, чтобы запустить

**Comment by compartia** [comment]
Спасибо!
собрал с таргет 8
но опция -i не работает что-то
из командной строки можно ее запускать так, чтобы без сервера или пока только сервером?

**Comment by SergeyShalaevsky** [comment]
да, я командную строку для себя делал :)
текущая сборка только сервер, но если очень надо, то можно из джарника достать папки lib и classes и запустить так: java -cp classes;lib/* com.nemo.document.parser.App -i <путь к файлу>

Если ее никак не проапгрейдить, то в понедельник выложу на сервак, который будет виден наружу или опущу версию.
