### ISSUE TITLE
Incorrectly detected headers (v. 1.0.7)

### ISSUE THREAD

**Issue by compartia** [nemoware/document-parser#10]
doc:` /3 этап по правилам/Догвоор Е.docx`

on screenshot ☢️sign marks paragraph start
## screenshot 1
<img width="1025" alt="Capture d’écran 2019-10-05 à 11 26 31" src="https://user-images.githubusercontent.com/7677437/66249405-76103e80-e765-11e9-99e8-9c485a9ee75b.png">

## screenshot 2
<img width="874" alt="Capture d’écran 2019-10-05 à 11 26 00" src="https://user-images.githubusercontent.com/7677437/66249406-76a8d500-e765-11e9-9869-c3bddf68afd7.png">

**Comment by compartia** [comment]
### screenshot 3
`этап по правилам/Догвоор Р.docx`
<img width="822" alt="Capture d’écran 2019-10-05 à 12 07 25" src="https://user-images.githubusercontent.com/7677437/66249612-c63cd000-e768-11e9-90b0-0e6984d303b6.png">

**Comment by compartia** [comment]
### v 1.0.8
`Догвоор_Р.docx`

Может, выфельтровывать "заголовки", в которых слишком много переносов строки?

<img width="718" alt="Capture d’écran 2019-10-07 à 18 36 51" src="https://user-images.githubusercontent.com/7677437/66305288-92f96d00-e931-11e9-994a-782172de988b.png">

**Comment by SergeyShalaevsky** [comment]
Этот заголовок возник из таблицы и заголовков в ней, в текущей версии они сваливаются в 1 заголовок. Сделать вместо этого кучу параграфов?!

**Comment by compartia** [comment]
@SergeyShalaevsky Я сейчас прогоню на тысяче-другой доков, посмотрю статистику. Если окажется, что слишком много чрезмерно длинных заголовков, то пере-открою этот баг с комментариями

**Comment by SergeyShalaevsky** [comment]
тут вопрос скорее не в статистике, а как такие таблицы удобнее интерпретировать

**Comment by compartia** [comment]
пока :
90 из 620 доков  имеют заголовки длинной > 400 символов

**Comment by compartia** [comment]
### Все же довольно много "странных" заголовков (скриншоты)
-  длиннее 200 символов:
<img width="924" alt="Capture d’écran 2019-10-07 à 23 07 35" src="https://user-images.githubusercontent.com/7677437/66324123-7ff99380-e957-11e9-9f96-3eb4cbb94a9e.png">
- с двумя и более переносами строк:
<img width="899" alt="Capture d’écran 2019-10-07 à 23 05 52" src="https://user-images.githubusercontent.com/7677437/66324125-80922a00-e957-11e9-9d83-b29242de4e90.png">

**Comment by compartia** [comment]
## v1.1.5

### Протокол_СД_ 3.docx

@SergeyShalaevsky 

- [ ] issue 1
#### expected:
<img width="223" alt="Capture d’écran 2019-10-26 à 22 27 58" src="https://user-images.githubusercontent.com/7677437/67621167-55a54280-f840-11e9-82a8-3518859d7f0c.png">
#### actual:
![Uploading Capture d’écran 2019-10-26 à 22.26.18.png…]()

-- 
- [ ] issue 2 
Потеряна нумерация строк
#### expected:
<img width="283" alt="Capture d’écran 2019-10-26 à 22 33 42" src="https://user-images.githubusercontent.com/7677437/67621215-de23e300-f840-11e9-945b-a22d6b464530.png">

#### actual:
<img width="274" alt="Capture d’écran 2019-10-26 à 22 34 05" src="https://user-images.githubusercontent.com/7677437/67621220-f0058600-f840-11e9-8beb-0c96821b6a49.png">

**Comment by SergeyShalaevsky** [comment]
2. в текущей версии, в json добавляется только текст документа, нумерация, которая идет через разметку, не добавляется. Добавить? Если да, то что делать со списками, где вместо номеров стоят маркеры?

**Comment by SergeyShalaevsky** [comment]
1. насчет «ПРОТИВ» - __; и «ВОЗДЕРЖАЛСЯ» -___. - это вполне валидные заголовки, т.к. есть доки, где заголовки просто набраны капсом без каких-либо доп стилей

**Comment by compartia** [comment]
> 1. насчет «ПРОТИВ» - **; и «ВОЗДЕРЖАЛСЯ» -**_. - это вполне валидные заголовки, т.к. есть доки, где заголовки просто набраны капсом без каких-либо доп стилей

у меня определенная сложность с тем, что "результаты голосования" не заголовок

> в текущей версии, в json добавляется только текст документа, нумерация, которая идет через разметку, не добавляется. Добавить? Если да, то что делать со списками, где вместо номеров стоят маркеры?

Маркеры, видимо, там совершенно разные бывают.. ну может их заменять на символ "•" ? Пока не знаю, как лучше, но мне иногда нужно знать, что несколько предложений (абзацев) подряд являются частью одного блока (если они буллетпоинты).
В целом, чем ближе док к оригиналу, тем мне лучше.

**Comment by SergeyShalaevsky** [comment]
> у меня определенная сложность с тем, что "результаты голосования" не заголовок

эта проблема понятна, речь только про «ПРОТИВ» - ; и «ВОЗДЕРЖАЛСЯ» -_.

**Comment by compartia** [comment]
> > у меня определенная сложность с тем, что "результаты голосования" не заголовок
> 
> эта проблема понятна, речь только про «ПРОТИВ» - ; и «ВОЗДЕРЖАЛСЯ» -_.

там еще и «ЗА» бывают =) Раньше у меня были эвристики для понимния того, заголовок стровка или нет, были примерно такие понижающие вероятность -- заголовок не оканчивается на точку или СК,  заголовок содержит кавычки. Если на твоей стороне нет косвенных признаков того, что они не заголовки, то я, конечно, на своей стороне могу конкретно для протоколов эти «ПРОТИВ» не считать заголовками (сделать хардкод-хак).

**Comment by SergeyShalaevsky** [comment]
> там еще и «ЗА» бывают =) Раньше у меня были эвристики для понимния того, заголовок стровка или нет, были примерно такие понижающие вероятность -- заголовок не оканчивается на точку или СК, заголовок содержит кавычки. Если на твоей стороне нет косвенных признаков того, что они не заголовки, то я, конечно, на своей стороне могу конкретно для протоколов эти «ПРОТИВ» не считать заголовками (сделать хардкод-хак).

«ЗА» отсекаются из-за того, что мало букв для заголовка. Да, скорее всего тебе придется вводить некий список стоп-слов для определенных типов доков.

**Comment by compartia** [comment]
еще тут с этим не все однозначно (хотя, что считать заголовком раздела, а что -- просто жирным шрифтом -- вопрос довольно сложный)

```Протокол СД ГПН-Транспорт УПЦ.docx```

<img width="315" alt="Capture d’écran 2019-10-28 à 16 37 43" src="https://user-images.githubusercontent.com/7677437/67663864-615c4a80-f9a1-11e9-8f21-d8719d753a5e.png">
<img width="276" alt="Capture d’écran 2019-10-28 à 16 37 20" src="https://user-images.githubusercontent.com/7677437/67663865-61f4e100-f9a1-11e9-92d9-132460efd542.png">

**Comment by compartia** [comment]
> «ЗА» отсекаются из-за того, что мало букв для заголовка. Да, скорее всего тебе придется вводить некий список стоп-слов для определенных типов доков.

эээээ я что-то надеялся, что ты только на стилях ворда базируешься, а у тебя тоже гадания эвристические =). Я просто тут наобучал всяких рандом форестов уже на основе твоих заголовков -- ( https://github.com/nemoware/analyser/blob/dccbfcec20e8f88d4cb22076ba86f27057246588/headers_detector.py#L102 ) и выходит, что у меня угадывание на основе угадывания =)))

**Comment by SergeyShalaevsky** [comment]
> еще тут с этим не все однозначно (хотя, что считать заголовком раздела, а что -- просто жирным шрифтом -- вопрос довольно сложный)

на самом деле это баг текущей версии, я считаю заголовком любой болд, который распространяется на весь вордовый параграф.

**Comment by SergeyShalaevsky** [comment]
> эээээ я что-то надеялся, что ты только на стилях ворда базируешься, а у тебя тоже гадания эвристические =). Я просто тут наобучал всяких рандом форестов уже на основе твоих заголовков

да, но я могу убрать это ограничение если надо, просто явно не будет заголовков где 2-3 буквы.
