### ISSUE TITLE
Некорректно определяется тип уставов (v1.1.9)

### ISSUE THREAD

**Issue by compartia** [nemoware/document-parser#13]
скриншот:
<img width="1143" alt="Capture d’écran 2019-10-09 à 21 21 21" src="https://user-images.githubusercontent.com/7677437/66485142-dc38f080-eada-11e9-9168-b3224efb1058.png">

**Comment by SergeyShalaevsky** [comment]
это я уже тоже заметил...

**Comment by compartia** [comment]
И там еще виден неправдоподобный номер протокола. Кстати, у протоколов, это все же не номер, а возможна ссылка на номер договора.

**Comment by SergeyShalaevsky** [comment]
на самом деле это тоже устав. и как я понимаю у уставов номеров нет вообще :)

**Comment by compartia** [comment]
еще из замеченного:
- у пары уставов подозрительно мало параграфов (возможно, это те, экзотически-билингвические)
- даты уставов архиважны

<img width="1004" alt="Capture d’écran 2019-10-09 à 21 33 44" src="https://user-images.githubusercontent.com/7677437/66486063-806f6700-eadc-11e9-9978-94c19fa49012.png">

**Comment by SergeyShalaevsky** [comment]
у некоторых уставов дата не указана

**Comment by compartia** [comment]
v1.1.9:
определен как протокол, но это устав `ЕЮ Устав.docx`
<img width="495" alt="Capture d’écran 2019-11-12 à 12 31 10" src="https://user-images.githubusercontent.com/7677437/68642214-58927980-0548-11ea-8d4e-afb7794ed0b5.png">
