### ISSUE TITLE
Некорректно разделены договоры

### ISSUE THREAD

**Issue by compartia** [nemoware/document-parser#18]
- [ ]  `3 этап по правилам/Договор ИК.docx`
 - [ ] `3 этап по правилам/Договор _2_.docx`
 - [ ] `3 этап по правилам/Д_И.docx`

видимо, из-за того, что в тексте встретилось "Приложение №1"
см. скриншот

<img width="565" alt="Capture d’écran 2019-10-24 à 13 58 11" src="https://user-images.githubusercontent.com/7677437/67457554-95b0cd80-f666-11e9-99a8-7b47aa5d680d.png">

high prio

**Comment by compartia** [comment]
# v1.1.9

- `3 этап по правилам/O_final.docx`
<img width="300" alt="Capture d’écran 2019-11-08 à 09 31 45" src="https://user-images.githubusercontent.com/7677437/68441942-a0dd2f00-020a-11ea-812d-2e4901bfa1ab.png">

- `3 этап по правилам/ДД_7.docx`
<img width="565" alt="Capture d’écran 2019-11-08 à 09 33 19" src="https://user-images.githubusercontent.com/7677437/68442075-ec8fd880-020a-11ea-9342-8c328aaa5599.png">

- `3 этап по правилам/Договор 18.docx`
<img width="469" alt="Capture d’écran 2019-11-08 à 09 35 15" src="https://user-images.githubusercontent.com/7677437/68442167-1f39d100-020b-11ea-961b-9356c1e352bd.png">

- `3 этап по правилам/Договор 7.docx`
- `3 этап по правилам/Договор _6.docx`

**Comment by compartia** [comment]
Примечание: в версии 1.1.5 эти доки разделялись правильно

**Comment by SergeyShalaevsky** [comment]
В 3 этап по правилам/Договор 18.docx проблема в том, что заголовок приложения в текущей версии(и в 1.1.5 тоже) не имеет признаков заголовочности.
Такие заголовки можно определять, разве что по отступу слева, но тут есть риск, что кое-какой текст тоже может быть отнесен к заголовкам.

**Comment by compartia** [comment]
> не имеет признаков заголовочности.

а у тебя учитывается количество вертикального вайтспейса перед заголовком и/или признаки разрыва страницы?

**Comment by SergeyShalaevsky** [comment]
ни куча вертикальных вайтспейсов, ни разрыв старницы не гарантируют, что дальше будет заголовок, если ты намекаешь на -  всегда считать заголовком после разрыва или N переносов строки

**Comment by compartia** [comment]
> ни куча вертикальных вайтспейсов, ни разрыв старницы не гарантируют, что дальше будет заголовок,

это так, но и "признаки заголовка" не гарантируют, что это заголовок =)

а совокупность разрыв страницы + регэкс вида `Приложение № 1 к Договору <что-то> №<что-то> от <дата>.`
?

**Comment by SergeyShalaevsky** [comment]
я бы все же предпочел разделять определение заголовка и разбивку на суб-доки, и сколько в таком случае переносов подряд считать разрывом?
идея с отступом слева на фоне разрывов теперь мне не кажется такой уж плохой :)

**Comment by compartia** [comment]
> и сколько в таком случае переносов подряд считать разрывом

в ворде ж есть прямо символ разрыва страницы

**Comment by SergeyShalaevsky** [comment]
конечно есть, но не все авторы доков в курсе :)

**Comment by compartia** [comment]
> конечно есть, но не все авторы доков в курсе :)

если док совсем-совсем плохо отформатирован, то это вообще должно быть проблемой людей, а не нашей системы. Наша система может просто сказать "не смогла", а биолюди должны сделать некие выводы, что форматирование имеет смысл. Чем больше мы (компьютеры) прощаем людям кривоты, тем больше они кривят

**Comment by SergeyShalaevsky** [comment]
т.е. ты предлагаешь просто забить на случаи где разрыв имитирован через кучу переносов?

**Comment by compartia** [comment]
не совсем так.
куча переносов (даже не самая большая куча) как правило предшествует заголовку.
Но не является при этом признаком конца/начала дока.

я предлагаю считать то, что после "кучки переносов", с большой вероятностью заголовком.

**Comment by SergeyShalaevsky** [comment]
В 3 этап по правилам/Договор 18.docx между некоторыми приложениями всего 2 переноса строки, считаем их (2 переноса) за разрыв?

**Comment by SergeyShalaevsky** [comment]
добавлен признак заголовочности - большой отступ слева
