### ISSUE TITLE
1.1.8: Missing headers in charter

### ISSUE THREAD

**Issue by compartia** [nemoware/document-parser#19]
doc: `Устав - ГПН-Транспорт_ГОСА-2018.docx`

screenshot: 
<img width="619" alt="Capture d’écran 2019-11-05 à 10 34 08" src="https://user-images.githubusercontent.com/7677437/68174333-af340c80-ffb8-11e9-830d-d54a369609ef.png">

**Comment by SergeyShalaevsky** [comment]
fixed in 14cdf4f70d6f2f31eb1883ad921ebab2e3cf706f
