### ISSUE TITLE
v1.1.9: missing whitespace after header number

### ISSUE THREAD

**Issue by compartia** [nemoware/document-parser#20]
<img width="487" alt="Capture d’écran 2019-11-08 à 09 27 52" src="https://user-images.githubusercontent.com/7677437/68441776-2f9d7c00-020a-11ea-9eef-2e23b47b60b4.png">

**Comment by compartia** [comment]
<img width="345" alt="Capture d’écran 2019-11-08 à 09 32 35" src="https://user-images.githubusercontent.com/7677437/68442671-adfb1d80-020c-11ea-86ab-feaf8ca73e24.png">

**Comment by SergeyShalaevsky** [comment]
1. не увидел имени файла(-ов)
2. это док-парсер выдает номера с нулями?

**Comment by compartia** [comment]
> 1. не увидел имени файла(-ов)

это, похоже, ко всем файлам относится, где есть нумерация заголовков

> 2. это док-парсер выдает номера с нулями?

да, но мне больше всего мешают не нули, а склейки типа "6порядок разрешения", когда даже без точки

**Comment by SergeyShalaevsky** [comment]
с пробелами все ясно, я их буду добавлять
насчет без точки - это уже значит паттерн нумерации такой, точки, скобки и т.п. я беру их от туда.

**Comment by compartia** [comment]
<img width="435" alt="Capture d’écran 2019-11-12 à 12 37 15" src="https://user-images.githubusercontent.com/7677437/68642460-33523b00-0549-11ea-8ce6-8a753e4996ca.png">

**Comment by SergeyShalaevsky** [comment]
какой это документ?

**Comment by compartia** [comment]
> какой это документ?

это устав `ЕЮ Устав.docx`

**Comment by compartia** [comment]
v1.1.13

приклеены буллетпоинты
ФАЙЛ
`Устав ГПН-Новосибирск (НБ)_с СД.doc`

<img width="325" alt="Capture d’écran 2019-12-05 à 17 02 13" src="https://user-images.githubusercontent.com/7677437/70220239-383d8f80-1781-11ea-8c06-8191e5d1909c.png">

see also #26

**Comment by compartia** [comment]
<img width="682" alt="Capture d’écran 2019-12-05 à 17 09 05" src="https://user-images.githubusercontent.com/7677437/70220767-0bd64300-1782-11ea-9813-9511095ff414.png">
