### ISSUE TITLE
v1.1.10 Не отрезаны доп. соглашения

### ISSUE THREAD

**Issue by compartia** [nemoware/document-parser#22]
см. скришоты
<img width="611" alt="Capture d’écran 2019-11-18 à 17 28 29" src="https://user-images.githubusercontent.com/7677437/69040897-9b14f400-0a29-11ea-85b0-030169e6c4b0.png">
<img width="555" alt="Capture d’écran 2019-11-18 à 17 23 52" src="https://user-images.githubusercontent.com/7677437/69040902-9bad8a80-0a29-11ea-815f-211462e4ba5d.png">

**Comment by SergeyShalaevsky** [comment]
судя по коду я это вообще не делал :) Какие еще доки надо отрезать? все поддерживаемые?

**Comment by compartia** [comment]
> Какие еще доки надо отрезать? все поддерживаемые?

ну вот пока за все это время только доп. соглашения всплыли. Вообще, отрезать нужно, скорее, не хвост (приложения и иже) от головы, а голову (договор, протокол, итп) от хвоста.
