### ISSUE TITLE
v1.1.13 "Положение о филиале" определено как "устав"

### ISSUE THREAD

**Issue by compartia** [nemoware/document-parser#25]
не уверен, что это баг,
но лучше уточнить

файлы:
`1 пп. 34 п. 19.1_филиалы/Изменения в Положение о филиале АО.docx`
`1 пп. 34 п. 19.1_филиалы/Положение о филиале АО.docx`

**Comment by SergeyShalaevsky** [comment]
я что-то таких доков даже найти не могу у себя :(
