### ISSUE TITLE
Please replace None (null) with empty string "" if possible

### ISSUE THREAD

**Issue by compartia** [nemoware/document-parser#4]
is it possible to return **empty string** for the paragraph body instead of null when body is blank/empty?

<img width="449" alt="Capture d’écran 2019-09-18 à 09 25 06" src="https://user-images.githubusercontent.com/7677437/65096145-88b11680-d9f6-11e9-8ad1-6a6a4aaa92bb.png">

**Comment by compartia** [comment]
tested with "2. Договор по благ-ти Радуга.docx"

**Comment by SergeyShalaevsky** [comment]
в параграфах сделал, как говорил, но остался null в дате документа(с полпинка не получилось, возможно вернусь к этому позже)
