### ISSUE TITLE
отрезать АКТ ПРИЕМА-ПЕРЕДАЧИ

### ISSUE THREAD

**Issue by compartia** [nemoware/document-parser#43]

**Comment by compartia** [comment]
example: 
Примеры документов/20200226/2. Договор Метель_аренда.docx

**Comment by SergeyShalaevsky** [comment]
не очень понимаю смысл в этом отрезании, разве не проще решить уже в анализаторе, нужно смотреть это приложение или нет?!

**Comment by compartia** [comment]
смысл примерно тот же, что был при нарезании доков ранее -- анализатор не знает границ документов.
насколько я понимаю, в парсер достаточно вставить еще один тип доков и маркер резки, а вот анализатор менять сложнее и рискованнее -- анализатор предполагает, что в тексте 1 документ.

**Comment by SergeyShalaevsky** [comment]
но этот акт и так в отдельном доке, просто не анализируй его

**Comment by compartia** [comment]
да, но отрезан.
я ошибся.
сорри, закрываю.
