### ISSUE TITLE
Wrong document dates detected

### ISSUE THREAD

**Issue by compartia** [nemoware/document-parser#8]
16 docs 'have' `documentDate` before 2015

<img width="1077" alt="Capture d’écran 2019-09-25 à 13 32 06" src="https://user-images.githubusercontent.com/7677437/65571972-27121e80-df99-11e9-9208-dc12ca20560b.png">

example text :
 
<img width="456" alt="Capture d’écran 2019-09-25 à 13 47 12" src="https://user-images.githubusercontent.com/7677437/65572683-69d4f600-df9b-11e9-9ede-1f465c878d1a.png">

**Comment by compartia** [comment]
probably related to #7

**Comment by SergeyShalaevsky** [comment]
с датами не все гладко, в некоторых местах номера документов похожи на даты
